build_platform:
  linux_aarch64: linux_aarch64
provider:
  linux_aarch64: default
test: native_and_emulated
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
os_version:
  linux_aarch64: alma8
